version: "3"
services:
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth
    env_file:
      - ./src/.env
    container_name: db
    restart: always
  golang:
    image: golang
    build: ./src
    ports:
      - 8080:8080
    container_name: golang
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth
      - DATABASE_PORT=5432
    depends_on:
      - db
