version: "3"
services:
  auth-go-db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    container_name: auth-go-db
    restart: always
  auth-go-api:
    build: ./src
    image: auth-go-api
    ports:
      - 8080:8080
    container_name: auth-go-api
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
    depends_on:
      - auth-go-db
