version: "3"
services:
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    env_file:
      - ./src/.env
    container_name: db
    restart: always
  golang:
    image: golang
    build: ./src
    ports:
      - 8080:8080
    container_name: golang
    env_file:
      - ./src/.env
    depends_on:
      - db
